### ISSUE TITLE
want to help maintain (but confused about SDK updates)

### ISSUE THREAD

**Issue by small-eggs** [klukule/PaliaHook#4]
Hey Lukáš,

I have been using PaliaHook and I appreciate the work you've done on it. Palia just released a new version which is causing PaliaHook to crash. I am aware of Dumper 7 and have gotten it to extract Palia's SDK, but I am completely lost after five hours of trying to update PaliaHook with the new SDK files.

I am willing to help keep PaliaHook up to date with PR's when a new Palia update gets released, if only you could point me in the right direction on how to update the SDK. I see you've done it several times before -- could you explain your process from Dumper 7 to integrating with PaliaHook (PaliaSDK)?

**Comment by klukule** [comment]
Hey there, I was super busy over past week or so, so I did not have time to update the SDK until right now (already on github)...

For the future, even though I'm using modified version of dumper-7 to automate this kind of stuff... everything that I do can be done manually:

- Dump SDK
- Remove old contents of PaliaSDK
- Copy new SDK
- Remove all files starting with `BP_`, `WBP_` and `ABP_` (that's where most issues came from, though it's an overkill to remove everything for just few outliers, I just never bothered to figure out which files are the specific issue)
- Remove the `ListItem_SocialConnection_*` files as they are tied to previously removed BP files
- Remove all entries to removed files from SDK.hpp
- Add some warning suppressors to avoid bunch of spam warnings
- Modify K2_GetActorLocation to fix crash (mostly tied to the fact that we do stuff on RHI instead of Game thread)
- Expose some non-uproperty fiels in ULevel class
- Add IsValidLowLevel function to UObject

That's all, it can be done in like 2 minutes manually, I just embedded it directly to the dumper since I'm lazy.
